In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

sales_data = {
    "Experience_Years": [1, 3, 2, 4, 5, 1, 2, 6, 3, 4, 2, 5, 3, 1, 6, 2, 3, 4, 1, 5,
                         2, 4, 3, 6, 5, 1, 2, 3, 4, 6, 2, 3, 5, 1, 4, 6, 3, 5, 2, 1,
                         6, 4, 2, 5, 3, 1, 4, 6, 2, 3, 4, 5, 1, 6, 2, 3, 4, 5, 3, 2,
                         1, 6, 2, 4, 5, 3, 1, 2, 4, 6, 5, 2, 3, 1, 4, 6, 2, 3, 5, 4,
                         6, 2, 3, 1, 4, 2, 6, 3, 5, 2, 4, 1, 3, 2, 6, 5, 3, 4, 2, 1],

    "Calls_Made": [40, 55, 50, 65, 70, 38, 45, 75, 60, 68, 52, 72, 59, 39, 80, 47, 56, 66, 42, 71,
                   51, 64, 58, 77, 69, 43, 49, 53, 67, 74, 48, 55, 70, 40, 66, 79, 57, 73, 50, 41,
                   76, 65, 46, 69, 54, 37, 63, 78, 44, 52, 61, 70, 39, 81, 47, 58, 62, 72, 57, 46,
                   43, 79, 48, 65, 73, 56, 36, 48, 67, 76, 71, 49, 53, 38, 64, 80, 45, 54, 75, 63,
                   77, 46, 55, 41, 66, 50, 79, 56, 71, 48, 63, 37, 54, 49, 78, 70, 59, 66, 50, 42],

    "Meetings_Held": [10, 14, 12, 16, 17, 9, 11, 18, 13, 15, 11, 17, 13, 10, 19, 12, 14, 15, 10, 18,
                      11, 15, 13, 19, 16, 9, 11, 13, 16, 18, 12, 14, 17, 9, 15, 19, 13, 16, 12, 10,
                      18, 15, 11, 17, 13, 8, 14, 18, 10, 12, 14, 17, 9, 20, 12, 13, 14, 18, 14, 12,
                      10, 19, 12, 15, 17, 13, 9, 11, 16, 19, 18, 12, 13, 10, 15, 19, 11, 13, 17, 15,
                      18, 11, 13, 9, 15, 12, 19, 14, 18, 12, 15, 8, 13, 12, 19, 17, 14, 16, 12, 10],

    "Deals_Closed": [3, 5, 4, 6, 7, 2, 4, 8, 5, 6, 4, 7, 5, 3, 9, 4, 5, 6, 3, 7,
                     4, 6, 5, 8, 6, 2, 3, 5, 6, 8, 4, 5, 7, 3, 6, 9, 5, 7, 4, 3,
                     8, 6, 4, 7, 5, 2, 6, 8, 3, 5, 6, 7, 2, 9, 4, 5, 6, 8, 5, 4,
                     3, 9, 4, 6, 7, 5, 2, 4, 6, 9, 7, 4, 5, 2, 6, 9, 3, 5, 8, 6,
                     8, 4, 5, 3, 6, 4, 9, 5, 7, 4, 6, 2, 5, 4, 9, 7, 5, 6, 4, 3],

    "Training_Hours": [5, 3, 4, 2, 1, 6, 5, 0, 3, 2, 5, 1, 3, 6, 0, 4, 3, 2, 6, 1,
                       4, 2, 3, 0, 1, 6, 5, 3, 2, 0, 4, 3, 1, 5, 2, 0, 3, 1, 4, 6,
                       0, 2, 5, 1, 3, 6, 2, 0, 5, 4, 2, 1, 6, 0, 4, 3, 2, 0, 3, 5,
                       6, 0, 4, 2, 1, 3, 6, 5, 2, 0, 1, 4, 3, 6, 2, 0, 5, 3, 0, 2,
                       0, 4, 3, 6, 2, 5, 0, 3, 1, 4, 2, 6, 3, 4, 0, 1, 3, 2, 4, 6],

    "Sales_Amount": [50000, 62000, 56000, 70000, 75000, 47000, 52000, 80000, 63000, 69000,
                     54000, 74000, 61000, 48000, 83000, 55000, 60000, 68000, 49000, 76000,
                     53000, 67000, 59000, 81000, 73000, 46000, 51000, 57000, 71000, 79000,
                     55000, 62000, 74000, 48000, 70000, 82000, 61000, 75000, 54000, 47000,
                     79000, 69000, 52000, 73000, 60000, 45000, 68000, 80000, 50000, 56000,
                     66000, 72000, 46000, 84000, 55000, 59000, 67000, 80000, 61000, 53000,
                     48000, 83000, 55000, 69000, 75000, 61000, 45000, 52000, 70000, 83000,
                     76000, 54000, 58000, 46000, 70000, 85000, 47000, 60000, 79000, 72000,
                     81000, 53000, 58000, 47000, 71000, 54000, 85000, 59000, 76000, 56000,
                     70000, 45000, 58000, 55000, 84000, 76000, 62000, 69000, 54000, 49000]
}
df=pd.DataFrame(sales_data)
print(df)

    Experience_Years  Calls_Made  Meetings_Held  Deals_Closed  Training_Hours  \
0                  1          40             10             3               5
1                  3          55             14             5               3
2                  2          50             12             4               4
3                  4          65             16             6               2
4                  5          70             17             7               1
..               ...         ...            ...           ...             ...
95                 5          70             17             7               1
96                 3          59             14             5               3
97                 4          66             16             6               2
98                 2          50             12             4               4
99                 1          42             10             3               6

    Sales_Amount
0          50000
1          62000
2          56000
3          70000
4          75000
..           ...
95         76000
96         62000
97         69000
98         54000
99         49000

[100 rows x 6 columns]

In [4]:
x=df[["Experience_Years","Calls_Made","Meetings_Held","Deals_Closed","Training_Hours"]]
y=df["Sales_Amount"]
#Train- Test-Split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)

[46408.21074477 84804.56485932 75777.77924836 42970.30796154
 60090.81611025 47303.46118087 61549.57304973 80471.41163999
 54715.79018295 47288.42154895 47668.15041574 54501.93328252
 45125.49806861 46393.17111285 67669.01707869 74517.83957739
 51079.07013121 60090.81611025 61914.2622846  61350.75578122]

In [5]:
results=pd.DataFrame({"Actual":y_test,"Predicted":y_pred})
print(results)

    Actual     Predicted
83   47000  46408.210745
53   84000  84804.564859
70   76000  75777.779248
45   45000  42970.307962
44   60000  60090.816110
39   47000  47303.461181
22   59000  61549.573050
80   81000  80471.411640
10   54000  54715.790183
0    50000  47288.421549
18   49000  47668.150416
30   55000  54501.933283
73   46000  45125.498069
33   48000  46393.171113
90   70000  67669.017079
4    75000  74517.839577
76   47000  51079.070131
77   60000  60090.816110
12   61000  61914.262285
31   62000  61350.755781

In [6]:
# Step 8: R² Score
print("Model R² Score :",model.score(x_test,y_test))

Model R² Score : 0.9833228834833003